# Generated by Django 6.1 on 2026-09-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
