# Generated by Django 6.1 on 2026-09-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_recurringtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
