# Generated by Django 6.1 on 2026-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_account_user_alter_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_name_per_category'),
        ),
    ]
