# Generated by Django 6.1 on 2026-08-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_subcategory_unique_subcategory_name_per_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='finance.account'),
        ),
    ]
