# Generated by Django 6.1 on 2026-09-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
