# Generated by Django 6.1 on 2026-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_account_icon_alter_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_to_receive__lte', models.F('amount'))), name='amount_to_receive_lte_amount'),
        ),
    ]
