# Generated by Django 6.1 on 2026-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_transaction_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
