# Generated by Django 6.1 on 2026-08-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
