# Generated by Django 6.1 on 2026-09-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_news_newsread'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='action_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='news',
            name='action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, upload_to='news/'),
        ),
    ]
