# Generated by Django 6.1 on 2026-10-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_emailchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
