# Generated by Django 6.1 on 2026-10-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='time',
        ),
    ]
