# Generated by Django 6.1 on 2026-10-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_remove_recurringtransaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='next_run_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
