# Generated by Django 6.1 on 2026-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_alter_recurringtransaction_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
