# Generated by Django 6.1 on 2026-08-26 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(validators=[django.core.validators.MinValueValidator(0, 'Value must positive')])),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
