import {
    ArrowRightLeft,
    BadgeEuro,
    BadgePlus,
    Baby,
    Bike,
    Bone,
    BookOpen,
    Briefcase,
    BriefcaseBusiness,
    Building,
    Building2,
    Bus,
    Car,
    ChartLine,
    CircleHelp,
    CirclePlus,
    Clock3,
    Coins,
    Coffee,
    CreditCard,
    Dumbbell,
    Film,
    Fuel,
    Gamepad2,
    Gift,
    GraduationCap,
    Hammer,
    HandHeart,
    HeartHandshake,
    HeartPulse,
    Hotel,
    House,
    Landmark,
    Laptop,
    Map,
    MonitorPlay,
    Music,
    PackageOpen,
    PawPrint,
    Percent,
    Pill,
    Plane,
    Receipt,
    ReceiptText,
    Repeat,
    School,
    Shield,
    ShieldCheck,
    ShieldPlus,
    Shirt,
    ShoppingBag,
    ShoppingBasket,
    ShoppingCart,
    Smartphone,
    Sofa,
    Stethoscope,
    Syringe,
    Train,
    TrendingUp,
    Tv,
    Users,
    Utensils,
    UtensilsCrossed,
    Wallet,
    Waypoints,
    Wrench,
    Zap,
    Banknote,
    ChartNoAxesCombined,
    EllipsisVertical,
    PiggyBank,
    Plus,
    Clapperboard,
    Martini,
    Wifi,
    Droplets,
    PartyPopper,
} from "lucide-react";

export const iconMap = {
    // Categories
    house: House,
    car: Car,
    "utensils-crossed": UtensilsCrossed,
    "heart-pulse": HeartPulse,
    "shopping-bag": ShoppingBag,
    "gamepad-2": Gamepad2,
    "graduation-cap": GraduationCap,
    plane: Plane,
    users: Users,
    landmark: Landmark,
    "paw-print": PawPrint,
    "circle-help": CircleHelp,
    briefcase: Briefcase,
    "chart-line": ChartLine,
    building: Building,
    gift: Gift,
    "rotate-ccw": Repeat,
    "circle-plus": CirclePlus,
    "arrow-right-left": ArrowRightLeft,
    "party-popper": PartyPopper,

    // Subcategories
    receipt: Receipt,
    shield: Shield,
    hammer: Hammer,
    zap: Zap,
    fuel: Fuel,
    wrench: Wrench,
    "square-parking": Car, // fallback
    waypoints: Waypoints,
    "shield-check": ShieldCheck,
    bus: Bus,
    "badge-euro": BadgeEuro,
    "shopping-cart": ShoppingCart,
    utensils: Utensils,
    coffee: Coffee,
    bike: Bike,
    stethoscope: Stethoscope,
    pill: Pill,
    "shield-plus": ShieldPlus,
    dumbbell: Dumbbell,
    shirt: Shirt,
    smartphone: Smartphone,
    sofa: Sofa,
    "shopping-basket": ShoppingBasket,
    film: Film,
    tv: Tv,
    "book-open": BookOpen,
    music: Music,
    "monitor-play": MonitorPlay,
    school: School,
    hotel: Hotel,
    train: Train,
    map: Map,
    baby: Baby,
    "heart-handshake": HeartHandshake,
    "building-2": Building2,
    "credit-card": CreditCard,
    "receipt-text": ReceiptText,
    bone: Bone,
    syringe: Syringe,
    wallet: Wallet,
    "badge-plus": BadgePlus,
    "clock-3": Clock3,
    coins: Coins,
    percent: Percent,
    "trending-up": TrendingUp,
    "briefcase-business": BriefcaseBusiness,
    laptop: Laptop,
    "hand-heart": HandHeart,
    "package-open": PackageOpen,
    repeat: Repeat,
    banknote: Banknote,
    "piggy-bank": PiggyBank,
    plus: Plus,
    "chart-no-axes-combined": ChartNoAxesCombined,
    "ellipsis-vertical": EllipsisVertical,
    investment: ChartNoAxesCombined,
    clapperboard: Clapperboard,
    martini: Martini,
    wifi: Wifi,
    droplets: Droplets,
    credit_card: CreditCard,
    piggy_bank: PiggyBank,
};
