name: CI

on:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ci-only-secret-key
      DEBUG: "True"
      DB_NAME: financewebapp
      DB_USER: financewebapp
      DB_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
      DB_HOST: 127.0.0.1
      DB_PORT: 5432

    services:
      postgres:
        image: postgres:17-alpine

        env:
          POSTGRES_DB: financewebapp
          POSTGRES_USER: financewebapp
          POSTGRES_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U financewebapp -d financewebapp"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Django checks
        working-directory: backend
        run: python manage.py check

      - name: Backend tests
        working-directory: backend
        run: python manage.py test

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Frontend lint
        working-directory: frontend
        run: npm run lint

      - name: Frontend build
        working-directory: frontend
        run: npm run build
